#!/usr/bin/env python3
"""Insert Prompts CSS styles into styles.css"""

# Read the file
with open('C:/Projects/3hours/admin/static/styles.css', 'r', encoding='utf-8') as f:
    lines = f.readlines()

# Find the line with "/* Responsive */"
insert_index = None
for i, line in enumerate(lines):
    if line.strip() == '/* Responsive */':
        insert_index = i
        break

if insert_index is None:
    print('ERROR: Could not find /* Responsive */ comment')
    exit(1)

# The CSS to insert
new_css_lines = [
    '/* Prompts Page */\n',
    '.prompts-container {\n',
    '    display: grid;\n',
    '    grid-template-columns: 280px 1fr;\n',
    '    gap: 20px;\n',
    '    height: calc(100vh - 180px);\n',
    '    min-height: 500px;\n',
    '}\n',
    '\n',
    '.prompts-list {\n',
    '    background: var(--card-bg);\n',
    '    border-radius: 12px;\n',
    '    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);\n',
    '    overflow: hidden;\n',
    '    display: flex;\n',
    '    flex-direction: column;\n',
    '}\n',
    '\n',
    '.prompts-list h3 {\n',
    '    padding: 16px 20px;\n',
    '    margin: 0;\n',
    '    font-size: 16px;\n',
    '    border-bottom: 1px solid var(--border-color);\n',
    '    background: var(--bg-color);\n',
    '}\n',
    '\n',
    '.prompts-list-items {\n',
    '    flex: 1;\n',
    '    overflow-y: auto;\n',
    '}\n',
    '\n',
    '.prompt-item {\n',
    '    padding: 14px 20px;\n',
    '    border-bottom: 1px solid var(--border-color);\n',
    '    cursor: pointer;\n',
    '    transition: background-color 0.2s;\n',
    '}\n',
    '\n',
    '.prompt-item:hover {\n',
    '    background-color: var(--bg-color);\n',
    '}\n',
    '\n',
    '.prompt-item.active {\n',
    '    background-color: rgba(79, 70, 229, 0.1);\n',
    '    border-left: 3px solid var(--primary-color);\n',
    '}\n',
    '\n',
    '.prompt-item-key {\n',
    '    font-weight: 600;\n',
    '    font-size: 14px;\n',
    '    margin-bottom: 4px;\n',
    '    color: var(--text-color);\n',
    '}\n',
    '\n',
    '.prompt-item-status {\n',
    '    display: flex;\n',
    '    align-items: center;\n',
    '    gap: 8px;\n',
    '    font-size: 12px;\n',
    '    color: var(--text-muted);\n',
    '}\n',
    '\n',
    '.prompt-version-badge {\n',
    '    display: inline-block;\n',
    '    padding: 2px 6px;\n',
    '    border-radius: 4px;\n',
    '    font-size: 10px;\n',
    '    font-weight: 500;\n',
    '    background: rgba(79, 70, 229, 0.1);\n',
    '    color: var(--primary-color);\n',
    '}\n',
    '\n',
    '.prompts-editor {\n',
    '    background: var(--card-bg);\n',
    '    border-radius: 12px;\n',
    '    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);\n',
    '    display: flex;\n',
    '    flex-direction: column;\n',
    '    overflow: hidden;\n',
    '}\n',
    '\n',
    '.prompts-editor-header {\n',
    '    padding: 16px 20px;\n',
    '    border-bottom: 1px solid var(--border-color);\n',
    '    background: var(--bg-color);\n',
    '    display: flex;\n',
    '    justify-content: space-between;\n',
    '    align-items: center;\n',
    '}\n',
    '\n',
    '.prompts-editor-header h3 {\n',
    '    margin: 0;\n',
    '    font-size: 16px;\n',
    '}\n',
    '\n',
    '.prompts-editor-actions {\n',
    '    display: flex;\n',
    '    gap: 8px;\n',
    '}\n',
    '\n',
    '.prompts-editor-content {\n',
    '    flex: 1;\n',
    '    display: flex;\n',
    '    flex-direction: column;\n',
    '    padding: 20px;\n',
    '    overflow-y: auto;\n',
    '}\n',
    '\n',
    '.prompt-textarea {\n',
    '    width: 100%;\n',
    '    min-height: 300px;\n',
    '    padding: 16px;\n',
    '    border: 1px solid var(--border-color);\n',
    '    border-radius: 8px;\n',
    "    font-family: 'Monaco', 'Menlo', 'Ubuntu Mono', monospace;\n",
    '    font-size: 13px;\n',
    '    line-height: 1.6;\n',
    '    resize: vertical;\n',
    '    background: var(--bg-color);\n',
    '    color: var(--text-color);\n',
    '}\n',
    '\n',
    '.prompt-textarea:focus {\n',
    '    outline: none;\n',
    '    border-color: var(--primary-color);\n',
    '    box-shadow: 0 0 0 3px rgba(79, 70, 229, 0.1);\n',
    '}\n',
    '\n',
    '.prompt-notes-input {\n',
    '    width: 100%;\n',
    '    padding: 10px 14px;\n',
    '    margin-top: 12px;\n',
    '    border: 1px solid var(--border-color);\n',
    '    border-radius: 8px;\n',
    '    font-size: 14px;\n',
    '}\n',
    '\n',
    '.prompt-notes-input:focus {\n',
    '    outline: none;\n',
    '    border-color: var(--primary-color);\n',
    '}\n',
    '\n',
    '.prompt-empty-state {\n',
    '    display: flex;\n',
    '    flex-direction: column;\n',
    '    align-items: center;\n',
    '    justify-content: center;\n',
    '    height: 100%;\n',
    '    color: var(--text-muted);\n',
    '    text-align: center;\n',
    '    padding: 40px;\n',
    '}\n',
    '\n',
    '.prompt-empty-state p {\n',
    '    font-size: 16px;\n',
    '    margin-bottom: 8px;\n',
    '}\n',
    '\n',
    '.prompt-empty-state small {\n',
    '    font-size: 13px;\n',
    '    opacity: 0.8;\n',
    '}\n',
    '\n',
    '/* Version History */\n',
    '.version-history {\n',
    '    margin-top: 20px;\n',
    '    padding-top: 20px;\n',
    '    border-top: 1px solid var(--border-color);\n',
    '}\n',
    '\n',
    '.version-history h4 {\n',
    '    margin: 0 0 12px 0;\n',
    '    font-size: 14px;\n',
    '    color: var(--text-muted);\n',
    '    text-transform: uppercase;\n',
    '    letter-spacing: 0.5px;\n',
    '}\n',
    '\n',
    '.version-list {\n',
    '    display: flex;\n',
    '    flex-direction: column;\n',
    '    gap: 8px;\n',
    '    max-height: 200px;\n',
    '    overflow-y: auto;\n',
    '}\n',
    '\n',
    '.version-item {\n',
    '    display: flex;\n',
    '    align-items: center;\n',
    '    justify-content: space-between;\n',
    '    padding: 10px 14px;\n',
    '    background: var(--bg-color);\n',
    '    border-radius: 8px;\n',
    '    border: 1px solid var(--border-color);\n',
    '}\n',
    '\n',
    '.version-item.active {\n',
    '    border-color: var(--success-color);\n',
    '    background: rgba(16, 185, 129, 0.05);\n',
    '}\n',
    '\n',
    '.version-header {\n',
    '    display: flex;\n',
    '    align-items: center;\n',
    '    gap: 10px;\n',
    '}\n',
    '\n',
    '.version-number {\n',
    '    font-weight: 600;\n',
    '    font-size: 14px;\n',
    '    color: var(--text-color);\n',
    '}\n',
    '\n',
    '.version-active-badge {\n',
    '    display: inline-block;\n',
    '    padding: 2px 8px;\n',
    '    border-radius: 4px;\n',
    '    font-size: 10px;\n',
    '    font-weight: 600;\n',
    '    text-transform: uppercase;\n',
    '    background: rgba(16, 185, 129, 0.1);\n',
    '    color: var(--success-color);\n',
    '}\n',
    '\n',
    '.version-meta {\n',
    '    font-size: 12px;\n',
    '    color: var(--text-muted);\n',
    '}\n',
    '\n',
    '.version-actions {\n',
    '    display: flex;\n',
    '    gap: 6px;\n',
    '}\n',
    '\n',
]

# Insert the new CSS before /* Responsive */
new_lines = lines[:insert_index] + new_css_lines + lines[insert_index:]

# Write back to file
with open('C:/Projects/3hours/admin/static/styles.css', 'w', encoding='utf-8') as f:
    f.writelines(new_lines)

print('SUCCESS: Prompts CSS styles added successfully')
print(f'Inserted {len(new_css_lines)} lines before line {insert_index + 1}')
